### ISSUE TITLE
Cannot build on Windows (AUD-990)

### ISSUE THREAD

**Issue by webtop** [espressif/esp-adf#268]
Hello, if I'm in the wrong place please let me know.

I just purchased a LyraT board and trying to build my first example ran into issues.
The example is the playmp3 code.

I'm on Windows 10, running make in an MSYS32 environment. When I "make menuconfig" I get the configuration menu as expected, set the correct parameters and save...no problem there.
However, when I initially ran just "make" I got an error about not having pyserial, so I installed that, then got a message about it being out of date...but then this:

`/e/Projects/esp/esp-idf/make/project.mk:62: esp-idf build system only supports MSYS2 in "MINGW32" mode. Consult the ESP-IDF documentation for details.
Toolchain path: /e/Libraries/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
WARNING: Toolchain version is not supported: esp-2019r2
Expected to see version: crosstool-ng-1.22.0-80-g6c4433a
Please check ESP-IDF setup instructions and update the toolchain, or proceed at your own risk.
WARNING: Compiler version is not supported: 8.2.0
Expected to see version(s): 5.2.0
Please check ESP-IDF setup instructions and update the toolchain, or proceed at your own risk.
/e/Projects/esp/esp-idf/make/project.mk:62: esp-idf build system only supports MSYS2 in "MINGW32" mode. Consult the ESP-IDF documentation for details.
WARNING: Toolchain version is not supported: esp-2019r2
Expected to see version: crosstool-ng-1.22.0-80-g6c4433a
Please check ESP-IDF setup instructions and update the toolchain, or proceed at your own risk.
WARNING: Compiler version is not supported: 8.2.0
Expected to see version(s): 5.2.0
Please check ESP-IDF setup instructions and update the toolchain, or proceed at your own risk.
don't know how to enumerate ttys on this system.
! I you know how the serial ports are named send this information to
! the author of this module:

sys.platform = 'msys'
os.name = 'posix'
pySerial version = 3.4

also add the naming scheme of the serial ports and with a bit luck you can get
this module running...
The installed version of pyserial appears to be too old for esptool.py (Python interpreter /usr/bin/python). Check the README for installation instructions.
Traceback (most recent call last):
  File "/e/Projects/esp/esp-idf/components/esptool_py/esptool/esptool.py", line 57, in <module>
    import serial.tools.list_ports as list_ports
  File "/usr/lib/python2.7/site-packages/serial/tools/list_ports.py", line 29, in <module>
    from serial.tools.list_ports_posix import comports
  File "/usr/lib/python2.7/site-packages/serial/tools/list_ports_posix.py", line 112, in <module>
    raise ImportError("Sorry: no implementation for your platform ('{}') available".format(os.name))
ImportError: Sorry: no implementation for your platform ('posix') available
make[1]: *** [/e/Projects/esp/esp-idf/components/esptool_py/Makefile.projbuild:59: /e/Projects/esp/play_mp3/build/bootloader/bootloader.bin] Error 1
make: *** [/e/Projects/esp/esp-idf/components/bootloader/Makefile.projbuild:41: /e/Projects/esp/play_mp3/build/bootloader/bootloader.bin] Error 2
`

The part that really confused me is that I have to use MSYS to compile, but then get "ImportError: Sorry: no implementation for your platform ('posix') available"...which is MSYS.

Could someone point me in the right direction to get an environment to develop?
I know this is not really a bug, but I'm new to espressif development boards and expected the instructions in the Get Started guide to work.

Thank you for any help, at all!
Paul

**Comment by webtop** [comment]
My version of Python is 2.7.5 should I start by updating that, and all components?

**Comment by webtop** [comment]
Well, I kept at it....changed the path to python in menuconfig so it used python3...initially that looked promising but then there was a PySerial version complaint, and pip refused to update it!

So I deleted everything in frustration, and will start over.

**Comment by webtop** [comment]
Ok, so I pulled down the fresh all-in-one zip file, put it in place, built the "hello world" app with no issues. I then went to build the sample "play_mp3" from the ADF SDK, and I get:

/bin/sh: python: command not found

And sure enough, in /usr/bin there is no python. There is however one in /mingw64/bin, although it's python 2/7 which is EOL in 1 month.

So far, so bad.

**Comment by webtop** [comment]
Sure is quiet and lonely in here...time for a small fire.  /x\

I resolved path issues by: ln -sf /mingw64/bin /usr/local/bin
Problem now is that packages are not satisfied...cryptography
pip install cryptography>=2.1.4 results in: TypeError: '>=' not supported between instances of 'NoneType' and 'str'

What I don't understand is: if you ship a version of msys, why on earth would you not pre-load the packages needed to run the examples?

Create a virtualenv and include it!

Clearly this is futile, so I'll just return the dev board and try someone else......thx, not!
